version: "3"

tasks:
  default: task lint test fmt

  clean:
    cmds:
      - go clean

  dep:
    cmds:
      - go install honnef.co/go/tools/cmd/staticcheck@latest
      - go install github.com/segmentio/golines@latest
      - go install github.com/securego/gosec/v2/cmd/gosec@latest
      - go install github.com/alexkohler/nakedret/cmd/nakedret@latest

  fmt:
    cmds:
      - go fmt ./...
      - golines -m 80 --shorten-comments -w .

  lint:
    cmds:
      - go vet ./...
      - staticcheck ./...
      - gosec -fmt=golint -quiet ./...
      - nakedret ./...

  test:
    cmds:
      - go test -v ./...
