on: [push, pull_request]

name: CI

jobs:
  test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.1"
      - name: Install Task
        uses: arduino/setup-task@v2
      - name: Install dependencies
        run: task dep
      - name: Lint
        run: task lint
      - name: Test
        run: task test
