on: [push, pull_request]

name: CI

jobs:
  test:
    name: Test suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
      - run: cargo install cargo-cmd
      - run: cargo cmd deps
      - run: cargo cmd test
